FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PLAYWRIGHT_BROWSERS_PATH=/app/playwright-browsers

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

RUN uv run playwright install-deps chromium
RUN uv run playwright install chromium

COPY . .
CMD ["uv", "run", "python", "-m", "src.scrapers.cron"]
